name: Build & Deploy

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 6 * * 2"

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "."
          ext: ".Dockerfile"
  Build:
    needs: list-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: get image info
        run: |
          echo "OWNER=${github.repository_owner,,}" | tr '[A-Z]' '[a-z]' >>${GITHUB_ENV}
          echo "IMAGENAME=./ubuntu-focal-desktop.Dockerfile" | sed 's/\.\///g' | sed 's/\.[^.]*$//' >>${GITHUB_ENV}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.paths }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.OWNER }}/kasm-workspace-${{ env.IMAGENAME }}:latest